; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.2.4
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit ADS1X15@^2.5.0
	adafruit/Adafruit SSD1306@^2.5.13
	suculent/AESLib@^2.3.6
	robtillaart/CRC@^1.0.3
	robtillaart/SHT85@0.5.1
